global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'customer_support_backend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['backend:8090']
